// Copyright (C) Cadwork. All rights reserved.

namespace Cadwork.Api.Enums;

public enum IfcPredefinedType
{
  None,
  Ceiling,
  Cladding,
  Flooring,
  Insulation,
  Membrane,
  Roofing,
  Sleeving,
  Wrapping,
  FootingBeam,
  PadFooting,
  PileCap,
  StripFooting,
  Cohesion,
  Friction,
  Support,
  Balustrade,
  Guardrail,
  Handrail,
  Baseslab,
  Floor,
  Landing,
  Roof,
  Beam,
  Hollowcore,
  Joist,
  Lintel,
  Spandrel,
  Tbeam,
  Complex,
  Element,
  Partial,
  ProvisionForSpace,
  ProvisionForVoid,
  Column,
  Pilaster,
  Molding,
  Skirtingboard,
  Door,
  Gate,
  TrapDoor,
  CaissonFoundation,
  Brace,
  Chord,
  Collar,
  Member,
  Mullion,
  Plate,
  Post,
  Purlin,
  Rafter,
  Stringer,
  Strut,
  Stud,
  Bored,
  Driven,
  Jetgrouting,
  CurtainPanel,
  Sheet,
  HalfTurnRamp,
  QuarterTurnRamp,
  SpiralRamp,
  StraightRunRamp,
  TwoQuarterTurnRamp,
  TwoStraightRunRamp,
  BarrelRoof,
  ButterflyRoof,
  DomeRoof,
  FlatRoof,
  Freeform,
  GableRoof,
  GambrelRoof,
  HippedGableRoof,
  HipRoof,
  MansardRoof,
  PavilionRoof,
  RainbowRoof,
  ShedRoof,
  CurvedRunStair,
  DoubleReturnStair,
  HalfTurnStair,
  HalfWindingStair,
  QuarterTurnStair,
  QuarterWindingStair,
  SpiralStair,
  StraightRunStair,
  ThreeQuarterTurnStair,
  ThreeQuarterWindingStair,
  TwoCurvedRunStair,
  TwoQuarterTurnStair,
  TwoQuarterWindingStair,
  TwoStraightRunStair,
  Curved,
  Spiral,
  Straight,
  Winder,
  ElementedWall,
  Movable,
  Parapet,
  Partitioning,
  PlumbingWall,
  Polygonal,
  Shear,
  SolidWall,
  Standard,
  Lightdome,
  Skylight,
  Window,
  Opening,
  Recess,
  Anchorbolt,
  Bolt,
  Dowel,
  Nail,
  NailPlate,
  Rivet,
  Screw,
  ShearConnector,
  Staple,
  StudShearConnector,
  Glue,
  Mortar,
  Weld,
  External,
  Gfa,
  Internal,
  Parking,
  Space,
  AccessoryAssembly,
  Arch,
  BeamGrid,
  BracedFrame,
  Girder,
  ReinforcementUnit,
  RigidFrame,
  SlabField,
  Truss,
  CableLadderSegment,
  CableTraySegment,
  CableTrunkingSegment,
  ConduitSegment,
  BusbarSegment,
  CableSegment,
  ConductorSegment,
  CoreSegment,
  FlexibleSegment,
  RigidSegment,
  Culvert,
  Gutter,
  Spool,
  AudioVisualOutlet,
  CommunicationsOutlet,
  PowerOutlet,
  DataOutlet,
  TelephoneOutlet,
  Anchoring,
  Edge,
  Ligature,
  Main,
  Punching,
  Ring,

  // IfcActuator_ELECTRICACTUATOR,
  // IfcActuator_HANDOPERATEDACTUATOR,
  // IfcActuator_HYDRAULICACTUATOR,
  // IfcActuator_PNEUMATICACTUATOR,
  // IfcActuator_THERMOSTATICACTUATOR,
  //
  // IfcAirTerminalBox_CONSTANTFLOW,
  // IfcAirTerminalBox_VARIABLEFLOWPRESSUREDEPENDANT,
  // IfcAirTerminalBox_VARIABLEFLOWPRESSUREINDEPENDANT,
  //
  // IfcAirTerminal_DIFFUSER,
  // IfcAirTerminal_GRILLE,
  // IfcAirTerminal_LOUVRE,
  // IfcAirTerminal_REGISTER,
  //
  // IfcAirToAirHeatRecovery_FIXEDPLATECOUNTERFLOWEXCHANGER,
  // IfcAirToAirHeatRecovery_FIXEDPLATECROSSFLOWEXCHANGER,
  // IfcAirToAirHeatRecovery_FIXEDPLATEPARALLELFLOWEXCHANGER,
  // IfcAirToAirHeatRecovery_ROTARYWHEEL,
  // IfcAirToAirHeatRecovery_RUNAROUNDCOILLOOP,
  // IfcAirToAirHeatRecovery_HEATPIPE,
  // IfcAirToAirHeatRecovery_TWINTOWERENTHALPYRECOVERYLOOPS,
  // IfcAirToAirHeatRecovery_THERMOSIPHONSEALEDTUBEHEATEXCHANGERS,
  // IfcAirToAirHeatRecovery_THERMOSIPHONCOILTYPEHEATEXCHANGERS,
  //
  // IfcAlarm_BELL,
  // IfcAlarm_BREAKGLASSBUTTON,
  // IfcAlarm_LIGHT,
  // IfcAlarm_MANUALPULLBOX,
  // IfcAlarm_SIREN,
  // IfcAlarm_WHISTLE,
  //
  // IfcAudioVisualAppliance_AMPLIFIER,
  // IfcAudioVisualAppliance_CAMERA,
  // IfcAudioVisualAppliance_DISPLAY,
  // IfcAudioVisualAppliance_MICROPHONE,
  // IfcAudioVisualAppliance_PLAYER,
  // IfcAudioVisualAppliance_PROJECTOR,
  // IfcAudioVisualAppliance_RECEIVER,
  // IfcAudioVisualAppliance_SPEAKER,
  // IfcAudioVisualAppliance_SWITCHER,
  // IfcAudioVisualAppliance_TELEPHONE,
  // IfcAudioVisualAppliance_TUNER,
  //
  // IfcBeam_BEAM,
  // IfcBeam_JOIST,
  // IfcBeam_HOLLOWCORE,
  // IfcBeam_LINTEL,
  // IfcBeam_SPANDREL,
  // IfcBeam_T_BEAM,
  //
  // IfcBoiler_WATER,
  // IfcBoiler_STEAM,
  //
  // IfcBuildingElementPart_INSULATION,
  // IfcBuildingElementPart_PRECASTPANEL,
  //
  // IfcBuildingElementProxy_COMPLEX,
  // IfcBuildingElementProxy_ELEMENT,
  // IfcBuildingElementProxy_PARTIAL,
  // IfcBuildingElementProxy_PROVISIONFORVOID,
  // IfcBuildingElementProxy_PROVISIONFORSPACE,
  //
  // IfcBuildingSystem_FENESTRATION,
  // IfcBuildingSystem_FOUNDATION,
  // IfcBuildingSystem_LOADBEARING,
  // IfcBuildingSystem_OUTERSHELL,
  // IfcBuildingSystem_SHADING,
  // IfcBuildingSystem_TRANSPORT,
  //
  // IfcCableCarrierFitting_BEND,
  // IfcCableCarrierFitting_CROSS,
  // IfcCableCarrierFitting_REDUCER,
  // IfcCableCarrierFitting_TEE,
  //
  // IfcCableCarrierSegment_CABLELADDERSEGMENT,
  // IfcCableCarrierSegment_CABLETRAYSEGMENT,
  // IfcCableCarrierSegment_CABLETRUNKINGSEGMENT,
  // IfcCableCarrierSegment_CONDUITSEGMENT,
  //
  // IfcCableFitting_CONNECTOR,
  // IfcCableFitting_ENTRY,
  // IfcCableFitting_EXIT,
  // IfcCableFitting_JUNCTION,
  // IfcCableFitting_TRANSITION,
  //
  // IfcCableSegment_BUSBARSEGMENT,
  // IfcCableSegment_CABLESEGMENT,
  // IfcCableSegment_CONDUCTORSEGMENT,
  // IfcCableSegment_CORESEGMENT,
  //
  // IfcChiller_AIRCOOLED,
  // IfcChiller_WATERCOOLED,
  // IfcChiller_HEATRECOVERY,
  //
  // IfcCoil_DXCOOLINGCOIL,
  // IfcCoil_ELECTRICHEATINGCOIL,
  // IfcCoil_GASHEATINGCOIL,
  // IfcCoil_HYDRONICCOIL,
  // IfcCoil_STEAMHEATINGCOIL,
  // IfcCoil_WATERCOOLINGCOIL,
  // IfcCoil_WATERHEATINGCOIL,
  //
  // IfcColumn_COLUMN,
  // IfcColumn_PILASTER,
  //
  // IfcCommunicationsAppliance_ANTENNA,
  // IfcCommunicationsAppliance_COMPUTER,
  // IfcCommunicationsAppliance_FAX,
  // IfcCommunicationsAppliance_GATEWAY,
  // IfcCommunicationsAppliance_MODEM,
  // IfcCommunicationsAppliance_NETWORKAPPLIANCE,
  // IfcCommunicationsAppliance_NETWORKBRIDGE,
  // IfcCommunicationsAppliance_NETWORKHUB,
  // IfcCommunicationsAppliance_PRINTER,
  // IfcCommunicationsAppliance_REPEATER,
  // IfcCommunicationsAppliance_ROUTER,
  // IfcCommunicationsAppliance_SCANNER,
  //
  // IfcCompressor_DYNAMIC,
  // IfcCompressor_RECIPROCATING,
  // IfcCompressor_ROTARY,
  // IfcCompressor_SCROLL,
  // IfcCompressor_TROCHOIDAL,
  // IfcCompressor_SINGLESTAGE,
  // IfcCompressor_BOOSTER,
  // IfcCompressor_OPENTYPE,
  // IfcCompressor_HERMETIC,
  // IfcCompressor_SEMIHERMETIC,
  // IfcCompressor_WELDEDSHELLHERMETIC,
  // IfcCompressor_ROLLINGPISTON,
  // IfcCompressor_ROTARYVANE,
  // IfcCompressor_SINGLESCREW,
  // IfcCompressor_TWINSCREW,
  //
  // IfcCondenser_AIRCOOLED,
  // IfcCondenser_EVAPORATIVECOOLED,
  // IfcCondenser_WATERCOOLED,
  // IfcCondenser_WATERCOOLEDBRAZEDPLATE,
  // IfcCondenser_WATERCOOLEDSHELLCOIL,
  // IfcCondenser_WATERCOOLEDSHELLTUBE,
  // IfcCondenser_WATERCOOLEDTUBEINTUBE,
  //
  // IfcConstructionEquipmentResource_DEMOLISHING,
  // IfcConstructionEquipmentResource_EARTHMOVING,
  // IfcConstructionEquipmentResource_ERECTING,
  // IfcConstructionEquipmentResource_HEATING,
  // IfcConstructionEquipmentResource_LIGHTING,
  // IfcConstructionEquipmentResource_PAVING,
  // IfcConstructionEquipmentResource_PUMPING,
  // IfcConstructionEquipmentResource_TRANSPORTING,
  //
  // IfcConstructionMaterialResource_AGGREGATES,
  // IfcConstructionMaterialResource_CONCRETE,
  // IfcConstructionMaterialResource_DRYWALL,
  // IfcConstructionMaterialResource_FUEL,
  // IfcConstructionMaterialResource_GYPSUM,
  // IfcConstructionMaterialResource_MASONRY,
  // IfcConstructionMaterialResource_METAL,
  // IfcConstructionMaterialResource_PLASTIC,
  // IfcConstructionMaterialResource_WOOD,
  //
  // IfcConstructionProductResource_ASSEMBLY,
  // IfcConstructionProductResource_FORMWORK,
  //
  // IfcController_FLOATING,
  // IfcController_PROGRAMMABLE,
  // IfcController_PROPORTIONAL,
  // IfcController_MULTIPOSITION,
  // IfcController_TWOPOSITION,
  //
  // IfcCooledBeam_ACTIVE,
  // IfcCooledBeam_PASSIVE,
  //
  // IfcCoolingTower_NATURALDRAFT,
  // IfcCoolingTower_MECHANICALINDUCEDDRAFT,
  // IfcCoolingTower_MECHANICALFORCEDDRAFT,
  //
  // IfcCovering_CEILING,
  // IfcCovering_FLOORING,
  // IfcCovering_CLADDING,
  // IfcCovering_ROOFING,
  // IfcCovering_MOLDING,
  // IfcCovering_SKIRTINGBOARD,
  // IfcCovering_INSULATION,
  // IfcCovering_MEMBRANE,
  // IfcCovering_SLEEVING,
  // IfcCovering_WRAPPING,
  //
  // IfcDamper_BACKDRAFTDAMPER,
  // IfcDamper_BALANCINGDAMPER,
  // IfcDamper_BLASTDAMPER,
  // IfcDamper_CONTROLDAMPER,
  // IfcDamper_FIREDAMPER,
  // IfcDamper_FIRESMOKEDAMPER,
  // IfcDamper_FUMEHOODEXHAUST,
  // IfcDamper_GRAVITYDAMPER,
  // IfcDamper_GRAVITYRELIEFDAMPER,
  // IfcDamper_RELIEFDAMPER,
  // IfcDamper_SMOKEDAMPER,
  //
  // IfcDiscreteAccessory_ANCHORPLATE,
  // IfcDiscreteAccessory_BRACKET,
  // IfcDiscreteAccessory_SHOE,
  //
  // IfcDistributionChamberElement_FORMEDDUCT,
  // IfcDistributionChamberElement_INSPECTIONCHAMBER,
  // IfcDistributionChamberElement_INSPECTIONPIT,
  // IfcDistributionChamberElement_MANHOLE,
  // IfcDistributionChamberElement_METERCHAMBER,
  // IfcDistributionChamberElement_SUMP,
  // IfcDistributionChamberElement_TRENCH,
  // IfcDistributionChamberElement_VALVECHAMBER,
  //
  // IfcDistributionPort_CABLE,
  // IfcDistributionPort_CABLECARRIER,
  // IfcDistributionPort_DUCT,
  // IfcDistributionPort_PIPE,
  //
  // IfcDoor_DOOR,
  // IfcDoor_GATE,
  // IfcDoor_TRAPDOOR,
  //
  // IfcDuctFitting_BEND,
  // IfcDuctFitting_CONNECTOR,
  // IfcDuctFitting_ENTRY,
  // IfcDuctFitting_EXIT,
  // IfcDuctFitting_JUNCTION,
  // IfcDuctFitting_OBSTRUCTION,
  // IfcDuctFitting_TRANSITION,
  //
  // IfcDuctSegment_RIGIDSEGMENT,
  // IfcDuctSegment_FLEXIBLESEGMENT,
  //
  // IfcDuctSilencer_FLATOVAL,
  // IfcDuctSilencer_RECTANGULAR,
  // IfcDuctSilencer_ROUND,
  //
  // IfcElectricAppliance_DISHWASHER,
  // IfcElectricAppliance_ELECTRICCOOKER,
  // IfcElectricAppliance_FREESTANDINGELECTRICHEATER,
  // IfcElectricAppliance_FREESTANDINGFAN,
  // IfcElectricAppliance_FREESTANDINGWATERHEATER,
  // IfcElectricAppliance_FREESTANDINGWATERCOOLER,
  // IfcElectricAppliance_FREEZER,
  // IfcElectricAppliance_FRIDGE_FREEZER,
  // IfcElectricAppliance_HANDDRYER,
  // IfcElectricAppliance_KITCHENMACHINE,
  // IfcElectricAppliance_MICROWAVE,
  // IfcElectricAppliance_PHOTOCOPIER,
  // IfcElectricAppliance_REFRIGERATOR,
  // IfcElectricAppliance_TUMBLEDRYER,
  // IfcElectricAppliance_VENDINGMACHINE,
  // IfcElectricAppliance_WASHINGMACHINE,
  //
  // IfcElectricDistributionBoard_CONSUMERUNIT,
  // IfcElectricDistributionBoard_DISTRIBUTIONBOARD,
  // IfcElectricDistributionBoard_MOTORCONTROLCENTRE,
  // IfcElectricDistributionBoard_SWITCHBOARD,
  //
  // IfcElectricFlowStorageDevice_BATTERY,
  // IfcElectricFlowStorageDevice_CAPACITORBANK,
  // IfcElectricFlowStorageDevice_HARMONICFILTER,
  // IfcElectricFlowStorageDevice_INDUCTORBANK,
  // IfcElectricFlowStorageDevice_UPS,
  //
  // IfcElectricGenerator_CHP,
  // IfcElectricGenerator_ENGINEGENERATOR,
  // IfcElectricGenerator_STANDALONE,
  //
  // IfcElectricMotor_DC,
  // IfcElectricMotor_INDUCTION,
  // IfcElectricMotor_POLYPHASE,
  // IfcElectricMotor_RELUCTANCESYNCHRONOUS,
  // IfcElectricMotor_SYNCHRONOUS,
  //
  // IfcElementAssembly_ACCESSORY_ASSEMBLY,
  // IfcElementAssembly_ARCH,
  // IfcElementAssembly_BEAM_GRID,
  // IfcElementAssembly_BRACED_FRAME,
  // IfcElementAssembly_GIRDER,
  // IfcElementAssembly_REINFORCEMENT_UNIT,
  // IfcElementAssembly_RIGID_FRAME,
  // IfcElementAssembly_SLAB_FIELD,
  // IfcElementAssembly_TRUSS,
  //
  // IfcEngine_EXTERNALCOMBUSTION,
  // IfcEngine_INTERNALCOMBUSTION,
  //
  // IfcEvaporativeCooler_DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER,
  // IfcEvaporativeCooler_DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER,
  // IfcEvaporativeCooler_DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER,
  // IfcEvaporativeCooler_DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER,
  // IfcEvaporativeCooler_DIRECTEVAPORATIVEAIRWASHER,
  // IfcEvaporativeCooler_INDIRECTEVAPORATIVEPACKAGEAIRCOOLER,
  // IfcEvaporativeCooler_INDIRECTEVAPORATIVEWETCOIL,
  // IfcEvaporativeCooler_INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER,
  // IfcEvaporativeCooler_INDIRECTDIRECTCOMBINATION,
  //
  // IfcEvaporator_DIRECTEXPANSION,
  // IfcEvaporator_DIRECTEXPANSIONSHELLANDTUBE,
  // IfcEvaporator_DIRECTEXPANSIONTUBEINTUBE,
  // IfcEvaporator_DIRECTEXPANSIONBRAZEDPLATE,
  // IfcEvaporator_FLOODEDSHELLANDTUBE,
  // IfcEvaporator_SHELLANDCOIL,
  //
  // IfcExternalSpatialElement_EXTERNAL,
  // IfcExternalSpatialElement_EXTERNAL_EARTH,
  // IfcExternalSpatialElement_EXTERNAL_WATER,
  // IfcExternalSpatialElement_EXTERNAL_FIRE,
  //
  // IfcFan_CENTRIFUGALFORWARDCURVED,
  // IfcFan_CENTRIFUGALRADIAL,
  // IfcFan_CENTRIFUGALBACKWARDINCLINEDCURVED,
  // IfcFan_CENTRIFUGALAIRFOIL,
  // IfcFan_TUBEAXIAL,
  // IfcFan_VANEAXIAL,
  // IfcFan_PROPELLORAXIAL,
  //
  // IfcFastener_GLUE,
  // IfcFastener_MORTAR,
  // IfcFastener_WELD,
  //
  // IfcFilter_AIRPARTICLEFILTER,
  // IfcFilter_COMPRESSEDAIRFILTER,
  // IfcFilter_ODORFILTER,
  // IfcFilter_OILFILTER,
  // IfcFilter_STRAINER,
  // IfcFilter_WATERFILTER,
  //
  // IfcFireSuppressionTerminal_BREECHINGINLET,
  // IfcFireSuppressionTerminal_FIREHYDRANT,
  // IfcFireSuppressionTerminal_HOSEREEL,
  // IfcFireSuppressionTerminal_SPRINKLER,
  // IfcFireSuppressionTerminal_SPRINKLERDEFLECTOR,
  //
  // IfcFlowInstrument_PRESSUREGAUGE,
  // IfcFlowInstrument_THERMOMETER,
  // IfcFlowInstrument_AMMETER,
  // IfcFlowInstrument_FREQUENCYMETER,
  // IfcFlowInstrument_POWERFACTORMETER,
  // IfcFlowInstrument_PHASEANGLEMETER,
  // IfcFlowInstrument_VOLTMETER_PEAK,
  // IfcFlowInstrument_VOLTMETER_RMS,
  //
  // IfcFlowMeter_ENERGYMETER,
  // IfcFlowMeter_GASMETER,
  // IfcFlowMeter_OILMETER,
  // IfcFlowMeter_WATERMETER,
  //
  // IfcFooting_CAISSON_FOUNDATION,
  // IfcFooting_FOOTING_BEAM,
  // IfcFooting_PAD_FOOTING,
  // IfcFooting_PILE_CAP,
  // IfcFooting_STRIP_FOOTING,
  //
  // IfcFurniture_CHAIR,
  // IfcFurniture_TABLE,
  // IfcFurniture_DESK,
  // IfcFurniture_BED,
  // IfcFurniture_FILECABINET,
  // IfcFurniture_SHELF,
  // IfcFurniture_SOFA,
  //
  // IfcGeographicElement_TERRAIN,
  //
  // IfcHeatExchanger_PLATE,
  // IfcHeatExchanger_SHELLANDTUBE,
  //
  // IfcHumidifier_STEAMINJECTION,
  // IfcHumidifier_ADIABATICAIRWASHER,
  // IfcHumidifier_ADIABATICPAN,
  // IfcHumidifier_ADIABATICWETTEDELEMENT,
  // IfcHumidifier_ADIABATICATOMIZING,
  // IfcHumidifier_ADIABATICULTRASONIC,
  // IfcHumidifier_ADIABATICRIGIDMEDIA,
  // IfcHumidifier_ADIABATICCOMPRESSEDAIRNOZZLE,
  // IfcHumidifier_ASSISTEDELECTRIC,
  // IfcHumidifier_ASSISTEDNATURALGAS,
  // IfcHumidifier_ASSISTEDPROPANE,
  // IfcHumidifier_ASSISTEDBUTANE,
  // IfcHumidifier_ASSISTEDSTEAM,
  //
  // IfcInterceptor_CYCLONIC,
  // IfcInterceptor_GREASE,
  // IfcInterceptor_OIL,
  // IfcInterceptor_PETROL,
  //
  // IfcJunctionBox_DATA,
  // IfcJunctionBox_POWER,
  //
  // IfcLamp_COMPACTFLUORESCENT,
  // IfcLamp_FLUORESCENT,
  // IfcLamp_HALOGEN,
  // IfcLamp_HIGHPRESSUREMERCURY,
  // IfcLamp_HIGHPRESSURESODIUM,
  // IfcLamp_LED,
  // IfcLamp_METALHALIDE,
  // IfcLamp_OLED,
  // IfcLamp_TUNGSTENFILAMENT,
  //
  // IfcLightFixture_POINTSOURCE,
  // IfcLightFixture_DIRECTIONSOURCE,
  // IfcLightFixture_SECURITYLIGHTING,
  //
  // IfcMechanicalFastener_ANCHORBOLT,
  // IfcMechanicalFastener_BOLT,
  // IfcMechanicalFastener_DOWEL,
  // IfcMechanicalFastener_NAIL,
  // IfcMechanicalFastener_NAILPLATE,
  // IfcMechanicalFastener_RIVET,
  // IfcMechanicalFastener_SCREW,
  // IfcMechanicalFastener_SHEARCONNECTOR,
  // IfcMechanicalFastener_STAPLE,
  // IfcMechanicalFastener_STUDSHEARCONNECTOR,
  //
  // IfcMedicalDevice_AIRSTATION,
  // IfcMedicalDevice_FEEDAIRUNIT,
  // IfcMedicalDevice_OXYGENGENERATOR,
  // IfcMedicalDevice_OXYGENPLANT,
  // IfcMedicalDevice_VACUUMSTATION,
  //
  // IfcMember_BRACE,
  // IfcMember_CHORD,
  // IfcMember_COLLAR,
  // IfcMember_MEMBER,
  // IfcMember_MULLION,
  // IfcMember_PLATE,
  // IfcMember_POST,
  // IfcMember_PURLIN,
  // IfcMember_RAFTER,
  // IfcMember_STRINGER,
  // IfcMember_STRUT,
  // IfcMember_STUD,
  //
  // IfcMotorConnection_BELTDRIVE,
  // IfcMotorConnection_COUPLING,
  // IfcMotorConnection_DIRECTDRIVE,
  //
  // IfcOpeningElement_OPENING,
  // IfcOpeningElement_RECESS,
  //
  // IfcOutlet_AUDIOVISUALOUTLET,
  // IfcOutlet_COMMUNICATIONSOUTLET,
  // IfcOutlet_POWEROUTLET,
  // IfcOutlet_DATAOUTLET,
  // IfcOutlet_TELEPHONEOUTLET,
  //
  // IfcPile_BORED,
  // IfcPile_DRIVEN,
  // IfcPile_JETGROUTING,
  // IfcPile_COHESION,
  // IfcPile_FRICTION,
  // IfcPile_SUPPORT,
  //
  // IfcPipeFitting_BEND,
  // IfcPipeFitting_CONNECTOR,
  // IfcPipeFitting_ENTRY,
  // IfcPipeFitting_EXIT,
  // IfcPipeFitting_JUNCTION,
  // IfcPipeFitting_OBSTRUCTION,
  // IfcPipeFitting_TRANSITION,
  //
  // IfcPipeSegment_CULVERT,
  // IfcPipeSegment_FLEXIBLESEGMENT,
  // IfcPipeSegment_RIGIDSEGMENT,
  // IfcPipeSegment_GUTTER,
  // IfcPipeSegment_SPOOL,
  //
  // IfcPlate_CURTAIN_PANEL,
  // IfcPlate_SHEET,
  //
  // IfcProtectiveDeviceTrippingUnit_ELECTRONIC,
  // IfcProtectiveDeviceTrippingUnit_ELECTROMAGNETIC,
  // IfcProtectiveDeviceTrippingUnit_RESIDUALCURRENT,
  // IfcProtectiveDeviceTrippingUnit_THERMAL,
  //
  // IfcProtectiveDevice_CIRCUITBREAKER,
  // IfcProtectiveDevice_EARTHLEAKAGECIRCUITBREAKER,
  // IfcProtectiveDevice_EARTHINGSWITCH,
  // IfcProtectiveDevice_FUSEDISCONNECTOR,
  // IfcProtectiveDevice_RESIDUALCURRENTCIRCUITBREAKER,
  // IfcProtectiveDevice_RESIDUALCURRENTSWITCH,
  // IfcProtectiveDevice_VARISTOR,
  //
  // IfcPump_CIRCULATOR,
  // IfcPump_ENDSUCTION,
  // IfcPump_SPLITCASE,
  // IfcPump_SUBMERSIBLEPUMP,
  // IfcPump_SUMPPUMP,
  // IfcPump_VERTICALINLINE,
  // IfcPump_VERTICALTURBINE,
  //
  // IfcRailing_HANDRAIL,
  // IfcRailing_GUARDRAIL,
  // IfcRailing_BALUSTRADE,
  //
  // IfcRampFlight_STRAIGHT,
  // IfcRampFlight_SPIRAL,
  //
  // IfcRamp_STRAIGHT_RUN_RAMP,
  // IfcRamp_TWO_STRAIGHT_RUN_RAMP,
  // IfcRamp_QUARTER_TURN_RAMP,
  // IfcRamp_TWO_QUARTER_TURN_RAMP,
  // IfcRamp_HALF_TURN_RAMP,
  // IfcRamp_SPIRAL_RAMP,
  //
  // IfcReinforcingBar_ANCHORING,
  // IfcReinforcingBar_EDGE,
  // IfcReinforcingBar_LIGATURE,
  // IfcReinforcingBar_MAIN,
  // IfcReinforcingBar_PUNCHING,
  // IfcReinforcingBar_RING,
  // IfcReinforcingBar_SHEAR,
  // IfcReinforcingBar_STUD,
  //
  // IfcRoof_FLAT_ROOF,
  // IfcRoof_SHED_ROOF,
  // IfcRoof_GABLE_ROOF,
  // IfcRoof_HIP_ROOF,
  // IfcRoof_HIPPED_GABLE_ROOF,
  // IfcRoof_GAMBREL_ROOF,
  // IfcRoof_MANSARD_ROOF,
  // IfcRoof_BARREL_ROOF,
  // IfcRoof_RAINBOW_ROOF,
  // IfcRoof_BUTTERFLY_ROOF,
  // IfcRoof_PAVILION_ROOF,
  // IfcRoof_DOME_ROOF,
  // IfcRoof_FREEFORM,
  //
  // IfcSanitaryTerminal_BATH,
  // IfcSanitaryTerminal_BIDET,
  // IfcSanitaryTerminal_CISTERN,
  // IfcSanitaryTerminal_SHOWER,
  // IfcSanitaryTerminal_SINK,
  // IfcSanitaryTerminal_SANITARYFOUNTAIN,
  // IfcSanitaryTerminal_TOILETPAN,
  // IfcSanitaryTerminal_URINAL,
  // IfcSanitaryTerminal_WASHHANDBASIN,
  // IfcSanitaryTerminal_WCSEAT,
  //
  // IfcSensor_COSENSOR,
  // IfcSensor_CO2SENSOR,
  // IfcSensor_CONDUCTANCESENSOR,
  // IfcSensor_CONTACTSENSOR,
  // IfcSensor_FIRESENSOR,
  // IfcSensor_FLOWSENSOR,
  // IfcSensor_FROSTSENSOR,
  // IfcSensor_GASSENSOR,
  // IfcSensor_HEATSENSOR,
  // IfcSensor_HUMIDITYSENSOR,
  // IfcSensor_IDENTIFIERSENSOR,
  // IfcSensor_IONCONCENTRATIONSENSOR,
  // IfcSensor_LEVELSENSOR,
  // IfcSensor_LIGHTSENSOR,
  // IfcSensor_MOISTURESENSOR,
  // IfcSensor_MOVEMENTSENSOR,
  // IfcSensor_PHSENSOR,
  // IfcSensor_PRESSURESENSOR,
  // IfcSensor_RADIATIONSENSOR,
  // IfcSensor_RADIOACTIVITYSENSOR,
  // IfcSensor_SMOKESENSOR,
  // IfcSensor_SOUNDSENSOR,
  // IfcSensor_TEMPERATURESENSOR,
  // IfcSensor_WINDSENSOR,
  //
  // IfcShadingDevice_JALOUSIE,
  // IfcShadingDevice_SHUTTER,
  // IfcShadingDevice_AWNING,
  //
  // IfcSlab_FLOOR,
  // IfcSlab_ROOF,
  // IfcSlab_LANDING,
  // IfcSlab_BASESLAB,
  //
  // IfcSolarDevice_SOLARCOLLECTOR,
  // IfcSolarDevice_SOLARPANEL,
  //
  // IfcSpaceHeater_CONVECTOR,
  // IfcSpaceHeater_RADIATOR,
  //
  // IfcSpace_SPACE,
  // IfcSpace_PARKING,
  // IfcSpace_GFA,
  // IfcSpace_INTERNAL,
  // IfcSpace_EXTERNAL,
  //
  // IfcSpatialZone_CONSTRUCTION,
  // IfcSpatialZone_FIRESAFETY,
  // IfcSpatialZone_LIGHTING,
  // IfcSpatialZone_OCCUPANCY,
  // IfcSpatialZone_SECURITY,
  // IfcSpatialZone_THERMAL,
  // IfcSpatialZone_TRANSPORT,
  // IfcSpatialZone_VENTILATION,
  //
  // IfcStackTerminal_BIRDCAGE,
  // IfcStackTerminal_COWL,
  // IfcStackTerminal_RAINWATERHOPPER,
  //
  // IfcStairFlight_STRAIGHT,
  // IfcStairFlight_WINDER,
  // IfcStairFlight_SPIRAL,
  // IfcStairFlight_CURVED,
  // IfcStairFlight_FREEFORM,
  //
  // IfcStair_STRAIGHT_RUN_STAIR,
  // IfcStair_TWO_STRAIGHT_RUN_STAIR,
  // IfcStair_QUARTER_WINDING_STAIR,
  // IfcStair_QUARTER_TURN_STAIR,
  // IfcStair_HALF_WINDING_STAIR,
  // IfcStair_HALF_TURN_STAIR,
  // IfcStair_TWO_QUARTER_WINDING_STAIR,
  // IfcStair_TWO_QUARTER_TURN_STAIR,
  // IfcStair_THREE_QUARTER_WINDING_STAIR,
  // IfcStair_THREE_QUARTER_TURN_STAIR,
  // IfcStair_SPIRAL_STAIR,
  // IfcStair_DOUBLE_RETURN_STAIR,
  // IfcStair_CURVED_RUN_STAIR,
  // IfcStair_TWO_CURVED_RUN_STAIR,
  //
  // IfcStructuralCurveMember_RIGID_JOINED_MEMBER,
  // IfcStructuralCurveMember_PIN_JOINED_MEMBER,
  // IfcStructuralCurveMember_CABLE,
  // IfcStructuralCurveMember_TENSION_MEMBER,
  // IfcStructuralCurveMember_COMPRESSION_MEMBER,
  //
  // IfcStructuralSurfaceActivity_CONST,
  // IfcStructuralSurfaceActivity_BILINEAR,
  // IfcStructuralSurfaceActivity_DISCRETE,
  // IfcStructuralSurfaceActivity_ISOCONTOUR,
  //
  // IfcStructuralSurfaceMember_BENDING_ELEMENT,
  // IfcStructuralSurfaceMember_MEMBRANE_ELEMENT,
  // IfcStructuralSurfaceMember_SHELL,
  //
  // IfcSubContractResource_PURCHASE,
  // IfcSubContractResource_WORK,
  //
  // IfcSurfaceFeature_MARK,
  // IfcSurfaceFeature_TAG,
  // IfcSurfaceFeature_TREATMENT,
  //
  // IfcSwitchingDevice_CONTACTOR,
  // IfcSwitchingDevice_DIMMERSWITCH,
  // IfcSwitchingDevice_EMERGENCYSTOP,
  // IfcSwitchingDevice_KEYPAD,
  // IfcSwitchingDevice_MOMENTARYSWITCH,
  // IfcSwitchingDevice_SELECTORSWITCH,
  // IfcSwitchingDevice_STARTER,
  // IfcSwitchingDevice_SWITCHDISCONNECTOR,
  // IfcSwitchingDevice_TOGGLESWITCH,
  //
  // IfcSystemFurnitureElement_PANEL,
  // IfcSystemFurnitureElement_WORKSURFACE,
  //
  // IfcTank_BASIN,
  // IfcTank_BREAKPRESSURE,
  // IfcTank_EXPANSION,
  // IfcTank_FEEDANDEXPANSION,
  // IfcTank_PRESSUREVESSEL,
  // IfcTank_STORAGE,
  // IfcTank_VESSEL,
  //
  // IfcTendonAnchor_COUPLER,
  // IfcTendonAnchor_FIXED_END,
  // IfcTendonAnchor_TENSIONING_END,
  //
  // IfcTendon_BAR,
  // IfcTendon_COATED,
  // IfcTendon_STRAND,
  // IfcTendon_WIRE,
  //
  // IfcTransformer_CURRENT,
  // IfcTransformer_FREQUENCY,
  // IfcTransformer_INVERTER,
  // IfcTransformer_RECTIFIER,
  // IfcTransformer_VOLTAGE,
  //
  // IfcTransportElement_ELEVATOR,
  // IfcTransportElement_ESCALATOR,
  // IfcTransportElement_MOVINGWALKWAY,
  // IfcTransportElement_CRANEWAY,
  // IfcTransportElement_LIFTINGGEAR,
  //
  // IfcTubeBundle_FINNED,
  //
  // IfcUnitaryControlElement_ALARMPANEL,
  // IfcUnitaryControlElement_CONTROLPANEL,
  // IfcUnitaryControlElement_GASDETECTIONPANEL,
  // IfcUnitaryControlElement_INDICATORPANEL,
  // IfcUnitaryControlElement_MIMICPANEL,
  // IfcUnitaryControlElement_HUMIDISTAT,
  // IfcUnitaryControlElement_THERMOSTAT,
  // IfcUnitaryControlElement_WEATHERSTATION,
  //
  // IfcUnitaryEquipment_AIRHANDLER,
  // IfcUnitaryEquipment_AIRCONDITIONINGUNIT,
  // IfcUnitaryEquipment_DEHUMIDIFIER,
  // IfcUnitaryEquipment_SPLITSYSTEM,
  // IfcUnitaryEquipment_ROOFTOPUNIT,
  //
  // IfcValve_AIRRELEASE,
  // IfcValve_ANTIVACUUM,
  // IfcValve_CHANGEOVER,
  // IfcValve_CHECK,
  // IfcValve_COMMISSIONING,
  // IfcValve_DIVERTING,
  // IfcValve_DRAWOFFCOCK,
  // IfcValve_DOUBLECHECK,
  // IfcValve_DOUBLEREGULATING,
  // IfcValve_FAUCET,
  // IfcValve_FLUSHING,
  // IfcValve_GASCOCK,
  // IfcValve_GASTAP,
  // IfcValve_ISOLATING,
  // IfcValve_MIXING,
  // IfcValve_PRESSUREREDUCING,
  // IfcValve_PRESSURERELIEF,
  // IfcValve_REGULATING,
  // IfcValve_SAFETYCUTOFF,
  // IfcValve_STEAMTRAP,
  // IfcValve_STOPCOCK,
  //
  // IfcVibrationIsolator_COMPRESSION,
  // IfcVibrationIsolator_SPRING,
  //
  // IfcVoidingFeature_CUTOUT,
  // IfcVoidingFeature_NOTCH,
  // IfcVoidingFeature_HOLE,
  // IfcVoidingFeature_MITER,
  // IfcVoidingFeature_CHAMFER,
  // IfcVoidingFeature_EDGE,
  //
  // IfcWall_MOVABLE,
  // IfcWall_PARAPET,
  // IfcWall_PARTITIONING,
  // IfcWall_PLUMBINGWALL,
  // IfcWall_SHEAR,
  // IfcWall_SOLIDWALL,
  // IfcWall_STANDARD,
  // IfcWall_POLYGONAL,
  // IfcWall_ELEMENTEDWALL,
  //
  // IfcWasteTerminal_FLOORTRAP,
  // IfcWasteTerminal_FLOORWASTE,
  // IfcWasteTerminal_GULLYSUMP,
  // IfcWasteTerminal_GULLYTRAP,
  // IfcWasteTerminal_ROOFDRAIN,
  // IfcWasteTerminal_WASTEDISPOSALUNIT,
  // IfcWasteTerminal_WASTETRAP,
  //
  // IfcWindow_WINDOW,
  // IfcWindow_SKYLIGHT,
  // IfcWindow_LIGHTDOME,
}
